(require 'package)

(add-to-list 'package-archives '("melpa-stable" . "http://stable.melpa.org/packages/") t)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/") t)
(package-initialize)

(add-to-list 'load-path "~/.emacs.d/config/")
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(require 'setup-ui)
(require 'setup-helm)
(require 'setup-rainbow-delimiters)
(require 'setup-autosave)
(require 'setup-undo-tree)
(require 'setup-ensime)
(require 'setup-eldoc)
(require 'setup-functions)
(require 'setup-projectile)
(require 'setup-markdown)
(require 'setup-node)
(require 'setup-haskell)
(require 'setup-magit)
(require 'setup-go)
